FROM almalinux:9

ENV course="DevOps" \
    trainer="shivakumar"
    
ARG duration="120hrs"

RUN echo "Hi, Course is: ${course} , trainer is : ${trainer} , and duration is ${duration}"

CMD ["sleep", "1000"]