FROM visweshbonam/cmd:v1
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/daws-84s/notes/refs/heads/main/session-51.txt /usr/share/nginx/html/index.html
RUN chmod +r /usr/share/nginx/html/index.html
