FROM almalinux:9

ENV Course="Devops" \
    Trainer="shiva" 

ARG Period="120hrs"

ENV Period=$Period

RUN echo = "I am learning:${Course},trainer by :${Trainer} for duration:${Period}"

CMD ["sleep", "1000"]